### PR TITLE
Fix compatibility issues with the latest version (1.2.2) of deap

### PR DESCRIPTION
**Pull request by weixuanfu**
Fix issues in unit tests and these issues is documented in #623

### CODE REVIEW

**Comment by PGijsbers** [comment]
Hi,

I just started working at a new workspace, after configuring and downloading the required software to develop TPOT, I ran into issues with the unit tests.

Specifically, it failed two mutNodeReplacement tests because Primitives are not hashable. Is this one of the issues that you found, or should those unit tests be working already (on the latest development branch)?

Currently running Python 3.6.3 on Windows 10.

Full test output for those two failed tests:

======================================================================                                                  

ERROR: Assert that mutNodeReplacement() returns the correct type of mutation node in a fixed pipeline.  
   
Traceback (most recent call last):                                                                                        
File "...\Continuum\anaconda3\lib\site-packages\nose\case.py", line 197, in runTest            self.test(*self.arg)                                                                                                  
File "...\tpot\tests\tpot_tests.py", line 1760, in test_mutNodeReplacement                             
      diff_prims = list(set(new_prims_list).symmetric_difference(old_prims_list))     
                                   TypeError: unhashable type: 'Primitive'     
                                                                                                                                                                                                    ======================================================================                                              
    ERROR: Assert that mutNodeReplacement() returns the correct type of mutation node in a complex pipeline.           
                                          Traceback (most recent call last):              
                                                                          File "...\Continuum\anaconda3\lib\site-packages\nose\case.py", line 197, in runTest            self.test(*self.arg)  
                                                                                                File "...\tpot\tests\tpot_tests.py", line 1798, in test_mutNodeReplacement_2                  
                diff_prims = list(set(new_prims_list).symmetric_difference(old_prims_list))          
                               TypeError: unhashable type: 'Primitive'

**Comment by weixuanfu** [comment]
@PG-TUe I think the commits in this PR would fix this issue. Could you please merge/add/install them into your environment and have a try.

**Comment by PGijsbers** [comment]
Downgrading to 1.0.2.post2 fixed also fixed this issue :)
Do you still want me to try your PR in my environment, or should that be OK anyway?

**Comment by weixuanfu** [comment]
Thank you for the feedback. Please test the PR if you want to use the latest version of Deap. I think it will work.

**Comment by PGijsbers** [comment]
It did 👍

**Pull request merged**
