### PR TITLE
Support arbitrary column transformers on subset of columns

### PR DESCRIPTION
**Pull request by edwardyu**
## What does this PR do?

Wrap `sklearn.compose.ColumnTransformer` so that other preprocessors and transformers will work on a subset of columns. This will allow for automated feature selection as well.

## Where should the reviewer start?

`tpot.builtins.ColumnTransformer` and look at changes to `base.py` to dynamically modify `config_dict`

## How should this PR be tested?

Run classifier and regressor with `ColumnTransformer` enabled.

## What are the relevant issues?

#1110 #1078 

## Questions:

- Do the docs need to be updated?
Maybe, will let reviewer decide.

- Does this PR add new (Python) dependencies?
No

### CODE REVIEW

**Comment by weixuanfu** [comment]
Sorry for the late response. I drafted a comment last week but forgot to push the green comment button. 

Could you please a demo in docs_sources for using this new transformers? Thank you for this PR.

**Comment by edwardyu** [comment]
Documentation added

**Review by weixuanfu — CHANGES_REQUESTED** [review]
Neat! I think this PR is almost ready to merge to development branch. But I think it should be an optional operator instead of putting it in all configurations under `config` since the pipeline maybe very hard to read if the input dataset has hundreds of columns (too many `include_col_` in the pipeline). Please exclude it from build-in configurations of TPOT and add a small example like we did for [FeatureSetSelector](https://epistasislab.github.io/tpot/using/#featuresetselector-in-tpot). Thank you!

**Comment by edwardyu** [comment]
OK changes made. I agree, I was thinking a future feature could be making the ColumnTransformer export use the sklearn version instead of the TPOT version, since they are the same anyways and it would make the exported pipeline much more visually simpler.

**Review by weixuanfu — APPROVED** [review]
Thank you for this PR. I will merge it to dev branch first.

**Pull request merged**
