### PR TITLE
Add some global flag to raise config dict import errors. I view these…

### PR DESCRIPTION
**Pull request by cottrell**
… as dangerous when unraised. Global flag is not great, but somebody else probably knows the structure better.

PR as a discussion point. #104 comment was where this started. The error sounded like something else, not just a typo in the config dict key.

### CODE REVIEW

**Comment by weixuanfu** [comment]
Thank you for this PR. Could you please rebase this PR to development branch?

**Comment by cottrell** [comment]
rebased on development.

**Comment by weixuanfu** [comment]
Thank you for this PR. Those python 2.7 builds failed somehow. I will look into it.

**Comment by weixuanfu** [comment]
I preferred to use `verbosity` to  control whether TPOT should raise this error message. If verbosity>2 then the ImportError should raise if it happened. I merged this PR to dev branch .

**Pull request merged**
