### PR TITLE
Re-add tests to MANIFEST.in

### PR DESCRIPTION
**Pull request by bollwyvl**
## What does this PR do?

(Re-)Adds the tests to `MANIFEST.in`. There was a line for `tests.py` and `tests.csv`, but those aren't currently in the repo.

## Where should the reviewer start?

`python setup.py sdist | grep tests`

## How should this PR be tested?

Ensure that the above command includes the `tests/*.{py,csv}`

## Any background context you want to provide?

First off, thanks for all the hard work!

In packaging this for conda, it's helpful to have some idea of whether the package, as installed, actually does what it says on the tin!

Further, as this package has several optional dependencies which are tested, and all available with conda, it is useful to check whether those are on the up-and-up.

## Questions:

- Do the docs need to be updated?

no

- Does this PR add new (Python) dependencies?

no

### CODE REVIEW

**Comment by weixuanfu** [comment]
Thank you! It is weird that 2 ci tests on Linux failed. Any ideas?

**Comment by bollwyvl** [comment]
Eek... Looks like some Network weirdness for various package managers. I'd
try a restart of the job?

Probably possible to do some more caching...

**Comment by weixuanfu** [comment]
Hmm, I am not with my laptop now. Please try to push a null comment (e.g. “clean codes”) to restart the test.

**Comment by rhiever** [comment]
Build restarted.

**Comment by bollwyvl** [comment]
py36 without coverage failed again...

**Comment by bollwyvl** [comment]
Hooray! 💚

**Comment by rhiever** [comment]
Thanks @bollwyvl! Looks like the tests were timing out. Hopefully not a regular issue, otherwise we'll have to dig into the specific tests that are timing out.

**Comment by bollwyvl** [comment]
Groovy. Come `0.9.2`, we'll run the tests in the packaging step on `conda-forge`!

**Pull request merged**
