### PR TITLE
sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23

### PR DESCRIPTION
**Pull request by jamesmyatt**
## What does this PR do?
sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. This PR adds joblib as an explicit dependency.

joblib 0.10.3 is used as the minimum version since it is the version included in scikit-learn 0.18.1.
https://github.com/scikit-learn/scikit-learn/blob/a5ab948cbc366d705b1f8db8687c7162f51de22d/sklearn/externals/joblib/__init__.py#L119

## Where should the reviewer start?

tpot/base.py 

## How should this PR be tested?

Regular unit test suite

## Any background context you want to provide?

https://scikit-learn.org/stable/whats_new.html#id40

## What are the relevant issues?

None

## Screenshots (if appropriate)

N/A

## Questions:

- Do the docs need to be updated? Yes
- Does this PR add new (Python) dependencies? Yes

### CODE REVIEW

**Comment by weixuanfu** [comment]
Thank you! Nice catch!

**Review by weixuanfu — CHANGES_REQUESTED** [review]
Please add joblib installation into ci tests' configuration, [.appveyor.yml](https://github.com/EpistasisLab/tpot/blob/master/.appveyor.yml) and [ci/.travis_install.sh](https://github.com/EpistasisLab/tpot/blob/master/ci/.travis_install.sh)

**Comment by jamesmyatt** [comment]
Wow! that's a lot of places to change!

**Comment by jamesmyatt** [comment]
CI scripts updated. Coverage should not have changed.

**Pull request merged**
